/* 회원 */
CREATE TABLE MY_SCHEMA.TABLE (
);

COMMENT ON TABLE MY_SCHEMA.TABLE IS '회원';

/* 일반회원 */
CREATE TABLE MY_SCHEMA.TABLE2 (
	id VARCHAr2(10) NOT NULL, /* ID */
	grade NUMBER(2) NOT NULL, /* 회원등급 */
	name VARCHAR2(5) NOT NULL, /* 이름 */
	id2 NUMBER(13) NOT NULL, /* 주민번호 */
	age NUMBER(3) NOT NULL, /* 나이 */
	birth NUMBER(6) NOT NULL, /* 생년월일 */
	phone NUMBER(11) NOT NULL, /* 핸드폰번호 */
	add VARCHAR2(20) NOT NULL /* 주소 */
);

CREATE UNIQUE INDEX MY_SCHEMA.PK_TABLE2
	ON MY_SCHEMA.TABLE2 (
		id ASC
	);

ALTER TABLE MY_SCHEMA.TABLE2
	ADD
		CONSTRAINT PK_TABLE2
		PRIMARY KEY (
			id
		);

COMMENT ON TABLE MY_SCHEMA.TABLE2 IS '일반회원';

COMMENT ON COLUMN MY_SCHEMA.TABLE2.id IS 'ID';

COMMENT ON COLUMN MY_SCHEMA.TABLE2.grade IS '회원등급';

COMMENT ON COLUMN MY_SCHEMA.TABLE2.name IS '이름';

COMMENT ON COLUMN MY_SCHEMA.TABLE2.id2 IS '주민번호';

COMMENT ON COLUMN MY_SCHEMA.TABLE2.age IS '나이';

COMMENT ON COLUMN MY_SCHEMA.TABLE2.birth IS '생년월일';

COMMENT ON COLUMN MY_SCHEMA.TABLE2.phone IS '핸드폰번호';

COMMENT ON COLUMN MY_SCHEMA.TABLE2.add IS '주소';

/* 딜러회원 */
CREATE TABLE MY_SCHEMA.TABLE3 (
	id VARCHAr2(10) NOT NULL, /* ID */
	d_grade NUMBER(2) NOT NULL, /* 회원등급 */
	d_name VARCHAR2(5) NOT NULL, /* 이름 */
	d_id2 NUMBER(13) NOT NULL, /* 주민번호 */
	d_age NUMBER(3) NOT NULL, /* 나이 */
	d_birth NUMBER(6) NOT NULL, /* 생년월일 */
	d_phone NUMBER(11) NOT NULL, /* 핸드폰번호 */
	d_add VARCHAR2(20) NOT NULL, /* 주소 */
	d_bgrade NUMBER(1) NOT NULL, /* 신용등급 */
	d_com NUMBER(10) NOT NULL /* 소속회사_연락처 */
);

CREATE UNIQUE INDEX MY_SCHEMA.PK_TABLE3
	ON MY_SCHEMA.TABLE3 (
		id ASC
	);

ALTER TABLE MY_SCHEMA.TABLE3
	ADD
		CONSTRAINT PK_TABLE3
		PRIMARY KEY (
			id
		);

COMMENT ON TABLE MY_SCHEMA.TABLE3 IS '딜러회원';

COMMENT ON COLUMN MY_SCHEMA.TABLE3.id IS 'ID';

COMMENT ON COLUMN MY_SCHEMA.TABLE3.d_grade IS '회원등급';

COMMENT ON COLUMN MY_SCHEMA.TABLE3.d_name IS '이름';

COMMENT ON COLUMN MY_SCHEMA.TABLE3.d_id2 IS '주민번호';

COMMENT ON COLUMN MY_SCHEMA.TABLE3.d_age IS '나이';

COMMENT ON COLUMN MY_SCHEMA.TABLE3.d_birth IS '생년월일';

COMMENT ON COLUMN MY_SCHEMA.TABLE3.d_phone IS '핸드폰번호';

COMMENT ON COLUMN MY_SCHEMA.TABLE3.d_add IS '주소';

COMMENT ON COLUMN MY_SCHEMA.TABLE3.d_bgrade IS '신용등급';

COMMENT ON COLUMN MY_SCHEMA.TABLE3.d_com IS '소속회사_연락처';

/* 등록 */
CREATE TABLE MY_SCHEMA.TABLE4 (
	add_no NUMBER(5) NOT NULL, /* 등록번호 */
	id VARCHAr2(10) NOT NULL, /* ID */
	co_no NUMBER(5) NOT NULL /* 차대번호 */
);

CREATE UNIQUE INDEX MY_SCHEMA.PK_TABLE4
	ON MY_SCHEMA.TABLE4 (
		add_no ASC
	);

ALTER TABLE MY_SCHEMA.TABLE4
	ADD
		CONSTRAINT PK_TABLE4
		PRIMARY KEY (
			add_no
		);

COMMENT ON TABLE MY_SCHEMA.TABLE4 IS '등록';

COMMENT ON COLUMN MY_SCHEMA.TABLE4.add_no IS '등록번호';

COMMENT ON COLUMN MY_SCHEMA.TABLE4.id IS 'ID';

COMMENT ON COLUMN MY_SCHEMA.TABLE4.co_no IS '차대번호';

/* 검색 */
CREATE TABLE MY_SCHEMA.TABLE5 (
);

COMMENT ON TABLE MY_SCHEMA.TABLE5 IS '검색';

/* 구입 */
CREATE TABLE MY_SCHEMA.TABLE6 (
);

COMMENT ON TABLE MY_SCHEMA.TABLE6 IS '구입';

/* 자동차 */
CREATE TABLE MY_SCHEMA.TABLE7 (
	co_no NUMBER(5) NOT NULL, /* 차대번호 */
	maker VARCHAR2(10) NOT NULL, /* 제조사 */
	model VARCHAR2(10) NOT NULL, /* 모델 */
	car_grade NUMBER(1) NOT NULL, /* 등급 */
	car_date DATE NOT NULL, /* 연식 */
	trans NUMBER(1) NOT NULL, /* 변속기 */
	color VARCHAR2(10) NOT NULL, /* 도색 */
	meter NUMBER(10) NOT NULL, /* 주행거리 */
	price NUMBER(20) NOT NULL /* 가격 */
);

CREATE UNIQUE INDEX MY_SCHEMA.PK_TABLE7
	ON MY_SCHEMA.TABLE7 (
		co_no ASC
	);

ALTER TABLE MY_SCHEMA.TABLE7
	ADD
		CONSTRAINT PK_TABLE7
		PRIMARY KEY (
			co_no
		);

COMMENT ON TABLE MY_SCHEMA.TABLE7 IS '자동차';

COMMENT ON COLUMN MY_SCHEMA.TABLE7.co_no IS '차대번호';

COMMENT ON COLUMN MY_SCHEMA.TABLE7.maker IS '제조사';

COMMENT ON COLUMN MY_SCHEMA.TABLE7.model IS '모델';

COMMENT ON COLUMN MY_SCHEMA.TABLE7.car_grade IS '등급';

COMMENT ON COLUMN MY_SCHEMA.TABLE7.car_date IS '연식';

COMMENT ON COLUMN MY_SCHEMA.TABLE7.trans IS '변속기';

COMMENT ON COLUMN MY_SCHEMA.TABLE7.color IS '도색';

COMMENT ON COLUMN MY_SCHEMA.TABLE7.meter IS '주행거리';

COMMENT ON COLUMN MY_SCHEMA.TABLE7.price IS '가격';

/* 승용차 */
CREATE TABLE MY_SCHEMA.TABLE8 (
	co_no NUMBER(5) NOT NULL, /* 차대번호 */
	size VARCHAR2(5) NOT NULL /* 크기 */
);

CREATE UNIQUE INDEX MY_SCHEMA.PK_TABLE8
	ON MY_SCHEMA.TABLE8 (
		co_no ASC
	);

ALTER TABLE MY_SCHEMA.TABLE8
	ADD
		CONSTRAINT PK_TABLE8
		PRIMARY KEY (
			co_no
		);

COMMENT ON TABLE MY_SCHEMA.TABLE8 IS '승용차';

COMMENT ON COLUMN MY_SCHEMA.TABLE8.co_no IS '차대번호';

COMMENT ON COLUMN MY_SCHEMA.TABLE8.size IS '크기';

/* 승합차 */
CREATE TABLE MY_SCHEMA.TABLE9 (
	co_no NUMBER(5) NOT NULL, /* 차대번호 */
	p_num NUMBER(2) NOT NULL /* 인승 */
);

CREATE UNIQUE INDEX MY_SCHEMA.PK_TABLE9
	ON MY_SCHEMA.TABLE9 (
		co_no ASC
	);

ALTER TABLE MY_SCHEMA.TABLE9
	ADD
		CONSTRAINT PK_TABLE9
		PRIMARY KEY (
			co_no
		);

COMMENT ON TABLE MY_SCHEMA.TABLE9 IS '승합차';

COMMENT ON COLUMN MY_SCHEMA.TABLE9.co_no IS '차대번호';

COMMENT ON COLUMN MY_SCHEMA.TABLE9.p_num IS '인승';

/* 스포츠카 */
CREATE TABLE MY_SCHEMA.TABLE10 (
	co_no NUMBER(5) NOT NULL, /* 차대번호 */
	engine NUMBER(2) NOT NULL /* 마력 */
);

CREATE UNIQUE INDEX MY_SCHEMA.PK_TABLE10
	ON MY_SCHEMA.TABLE10 (
		co_no ASC
	);

ALTER TABLE MY_SCHEMA.TABLE10
	ADD
		CONSTRAINT PK_TABLE10
		PRIMARY KEY (
			co_no
		);

COMMENT ON TABLE MY_SCHEMA.TABLE10 IS '스포츠카';

COMMENT ON COLUMN MY_SCHEMA.TABLE10.co_no IS '차대번호';

COMMENT ON COLUMN MY_SCHEMA.TABLE10.engine IS '마력';

/* 화물차 */
CREATE TABLE MY_SCHEMA.TABLE11 (
);

COMMENT ON TABLE MY_SCHEMA.TABLE11 IS '화물차';

/* 화물차 */
CREATE TABLE MY_SCHEMA.TABLE12 (
	co_no NUMBER(5) NOT NULL, /* 차대번호 */
	shape VARCHAR2(10) NOT NULL /* 형태 */
);

CREATE UNIQUE INDEX MY_SCHEMA.PK_TABLE12
	ON MY_SCHEMA.TABLE12 (
		co_no ASC
	);

ALTER TABLE MY_SCHEMA.TABLE12
	ADD
		CONSTRAINT PK_TABLE12
		PRIMARY KEY (
			co_no
		);

COMMENT ON TABLE MY_SCHEMA.TABLE12 IS '화물차';

COMMENT ON COLUMN MY_SCHEMA.TABLE12.co_no IS '차대번호';

COMMENT ON COLUMN MY_SCHEMA.TABLE12.shape IS '형태';

/* 화물차2 */
CREATE TABLE MY_SCHEMA.TABLE13 (
);

COMMENT ON TABLE MY_SCHEMA.TABLE13 IS '화물차2';

/* 거래 */
CREATE TABLE MY_SCHEMA.TABLE14 (
	co_no NUMBER(5) NOT NULL, /* 거래번호 */
	c_no NUMBER(5) NOT NULL, /* 차대번호 */
	id VARCHAr2(10) NOT NULL, /* ID */
	co_date DATE NOT NULL, /* 구매일시 */
	co_true NUMBER(1) NOT NULL /* 결제확인 */
);

CREATE UNIQUE INDEX MY_SCHEMA.PK_TABLE14
	ON MY_SCHEMA.TABLE14 (
		co_no ASC
	);

ALTER TABLE MY_SCHEMA.TABLE14
	ADD
		CONSTRAINT PK_TABLE14
		PRIMARY KEY (
			co_no
		);

COMMENT ON TABLE MY_SCHEMA.TABLE14 IS '거래';

COMMENT ON COLUMN MY_SCHEMA.TABLE14.co_no IS '거래번호';

COMMENT ON COLUMN MY_SCHEMA.TABLE14.c_no IS '차대번호';

COMMENT ON COLUMN MY_SCHEMA.TABLE14.id IS 'ID';

COMMENT ON COLUMN MY_SCHEMA.TABLE14.co_date IS '구매일시';

COMMENT ON COLUMN MY_SCHEMA.TABLE14.co_true IS '결제확인';

/* 검사 */
CREATE TABLE MY_SCHEMA.TABLE15 (
	co_no NUMBER(5) NOT NULL, /* 차대번호 */
	accident NUMBER(1) NOT NULL, /* 사고여부 */
	drive NUMBER(1) NOT NULL, /* 주행진단 */
	dashboard NUMBER(1) NOT NULL, /* 계기판수리/교체흔적 */
	regi NUMBER(1) NOT NULL, /* 등록증확인 */
	in NUMBER(1) NOT NULL, /* 차량내부진단 */
	out NUMBER(1) NOT NULL, /* 차량외부진단 */
	option NUMBER(1) NOT NULL, /* 옵션진단 */
	engine NUMBER(1) NOT NULL, /* 엔진룸진단 */
	bottom NUMBER(1) NOT NULL /* 하부진단 */
);

CREATE UNIQUE INDEX MY_SCHEMA.PK_TABLE15
	ON MY_SCHEMA.TABLE15 (
		co_no ASC
	);

ALTER TABLE MY_SCHEMA.TABLE15
	ADD
		CONSTRAINT PK_TABLE15
		PRIMARY KEY (
			co_no
		);

COMMENT ON TABLE MY_SCHEMA.TABLE15 IS '검사';

COMMENT ON COLUMN MY_SCHEMA.TABLE15.co_no IS '차대번호';

COMMENT ON COLUMN MY_SCHEMA.TABLE15.accident IS '사고여부';

COMMENT ON COLUMN MY_SCHEMA.TABLE15.drive IS '주행진단';

COMMENT ON COLUMN MY_SCHEMA.TABLE15.dashboard IS '계기판수리/교체흔적';

COMMENT ON COLUMN MY_SCHEMA.TABLE15.regi IS '등록증확인';

COMMENT ON COLUMN MY_SCHEMA.TABLE15.in IS '차량내부진단';

COMMENT ON COLUMN MY_SCHEMA.TABLE15.out IS '차량외부진단';

COMMENT ON COLUMN MY_SCHEMA.TABLE15.option IS '옵션진단';

COMMENT ON COLUMN MY_SCHEMA.TABLE15.engine IS '엔진룸진단';

COMMENT ON COLUMN MY_SCHEMA.TABLE15.bottom IS '하부진단';

/* 진단점검 */
CREATE TABLE MY_SCHEMA.TABLE16 (
);

COMMENT ON TABLE MY_SCHEMA.TABLE16 IS '진단점검';

/* 차종 */
CREATE TABLE MY_SCHEMA.TABLE17 (
	COL2 <지정 되지 않음> NOT NULL /* 차종 */
);

CREATE UNIQUE INDEX MY_SCHEMA.PK_TABLE17
	ON MY_SCHEMA.TABLE17 (
		COL2 ASC
	);

ALTER TABLE MY_SCHEMA.TABLE17
	ADD
		CONSTRAINT PK_TABLE17
		PRIMARY KEY (
			COL2
		);

COMMENT ON TABLE MY_SCHEMA.TABLE17 IS '차종';

COMMENT ON COLUMN MY_SCHEMA.TABLE17.COL2 IS '차종';

/* 광고 */
CREATE TABLE MY_SCHEMA.TABLE18 (
	ad_no NUMBER(5) NOT NULL, /* 광고번호 */
	add_no NUMBER(5) NOT NULL, /* 등록번호 */
	a_ex_date DATE NOT NULL /* 종료시일 */
);

CREATE UNIQUE INDEX MY_SCHEMA.PK_TABLE18
	ON MY_SCHEMA.TABLE18 (
		ad_no ASC
	);

ALTER TABLE MY_SCHEMA.TABLE18
	ADD
		CONSTRAINT PK_TABLE18
		PRIMARY KEY (
			ad_no
		);

COMMENT ON TABLE MY_SCHEMA.TABLE18 IS '광고';

COMMENT ON COLUMN MY_SCHEMA.TABLE18.ad_no IS '광고번호';

COMMENT ON COLUMN MY_SCHEMA.TABLE18.add_no IS '등록번호';

COMMENT ON COLUMN MY_SCHEMA.TABLE18.a_ex_date IS '종료시일';

/* 광고연장요청 */
CREATE TABLE MY_SCHEMA.TABLE19 (
	ad_no NUMBER(5) NOT NULL, /* 광고번호 */
	id VARCHAr2(10) NOT NULL, /* ID */
	c_date DATE NOT NULL /* 변경시일 */
);

CREATE UNIQUE INDEX MY_SCHEMA.PK_TABLE19
	ON MY_SCHEMA.TABLE19 (
		ad_no ASC
	);

ALTER TABLE MY_SCHEMA.TABLE19
	ADD
		CONSTRAINT PK_TABLE19
		PRIMARY KEY (
			ad_no
		);

COMMENT ON TABLE MY_SCHEMA.TABLE19 IS '광고연장요청';

COMMENT ON COLUMN MY_SCHEMA.TABLE19.ad_no IS '광고번호';

COMMENT ON COLUMN MY_SCHEMA.TABLE19.id IS 'ID';

COMMENT ON COLUMN MY_SCHEMA.TABLE19.c_date IS '변경시일';

/* 차량보증 */
CREATE TABLE MY_SCHEMA.TABLE20 (
	co_no NUMBER(5) NOT NULL, /* 거래번호 */
	g_ex_date DATE NOT NULL /* 보증종료일 */
);

CREATE UNIQUE INDEX MY_SCHEMA.PK_TABLE20
	ON MY_SCHEMA.TABLE20 (
		co_no ASC
	);

ALTER TABLE MY_SCHEMA.TABLE20
	ADD
		CONSTRAINT PK_TABLE20
		PRIMARY KEY (
			co_no
		);

COMMENT ON TABLE MY_SCHEMA.TABLE20 IS '차량보증';

COMMENT ON COLUMN MY_SCHEMA.TABLE20.co_no IS '거래번호';

COMMENT ON COLUMN MY_SCHEMA.TABLE20.g_ex_date IS '보증종료일';

ALTER TABLE MY_SCHEMA.TABLE4
	ADD
		CONSTRAINT FK_TABLE2_TO_TABLE4
		FOREIGN KEY (
			id
		)
		REFERENCES MY_SCHEMA.TABLE2 (
			id
		);

ALTER TABLE MY_SCHEMA.TABLE4
	ADD
		CONSTRAINT FK_TABLE3_TO_TABLE4
		FOREIGN KEY (
			id
		)
		REFERENCES MY_SCHEMA.TABLE3 (
			id
		);

ALTER TABLE MY_SCHEMA.TABLE4
	ADD
		CONSTRAINT FK_TABLE7_TO_TABLE4
		FOREIGN KEY (
			co_no
		)
		REFERENCES MY_SCHEMA.TABLE7 (
			co_no
		);

ALTER TABLE MY_SCHEMA.TABLE8
	ADD
		CONSTRAINT FK_TABLE7_TO_TABLE8
		FOREIGN KEY (
			co_no
		)
		REFERENCES MY_SCHEMA.TABLE7 (
			co_no
		);

ALTER TABLE MY_SCHEMA.TABLE9
	ADD
		CONSTRAINT FK_TABLE7_TO_TABLE9
		FOREIGN KEY (
			co_no
		)
		REFERENCES MY_SCHEMA.TABLE7 (
			co_no
		);

ALTER TABLE MY_SCHEMA.TABLE10
	ADD
		CONSTRAINT FK_TABLE7_TO_TABLE10
		FOREIGN KEY (
			co_no
		)
		REFERENCES MY_SCHEMA.TABLE7 (
			co_no
		);

ALTER TABLE MY_SCHEMA.TABLE12
	ADD
		CONSTRAINT FK_TABLE7_TO_TABLE12
		FOREIGN KEY (
			co_no
		)
		REFERENCES MY_SCHEMA.TABLE7 (
			co_no
		);

ALTER TABLE MY_SCHEMA.TABLE14
	ADD
		CONSTRAINT FK_TABLE2_TO_TABLE14
		FOREIGN KEY (
			id
		)
		REFERENCES MY_SCHEMA.TABLE2 (
			id
		);

ALTER TABLE MY_SCHEMA.TABLE14
	ADD
		CONSTRAINT FK_TABLE3_TO_TABLE14
		FOREIGN KEY (
			id
		)
		REFERENCES MY_SCHEMA.TABLE3 (
			id
		);

ALTER TABLE MY_SCHEMA.TABLE14
	ADD
		CONSTRAINT FK_TABLE7_TO_TABLE14
		FOREIGN KEY (
			c_no
		)
		REFERENCES MY_SCHEMA.TABLE7 (
			co_no
		);

ALTER TABLE MY_SCHEMA.TABLE15
	ADD
		CONSTRAINT FK_TABLE7_TO_TABLE15
		FOREIGN KEY (
			co_no
		)
		REFERENCES MY_SCHEMA.TABLE7 (
			co_no
		);

ALTER TABLE MY_SCHEMA.TABLE18
	ADD
		CONSTRAINT FK_TABLE4_TO_TABLE18
		FOREIGN KEY (
			add_no
		)
		REFERENCES MY_SCHEMA.TABLE4 (
			add_no
		);

ALTER TABLE MY_SCHEMA.TABLE18
	ADD
		CONSTRAINT FK_TABLE19_TO_TABLE18
		FOREIGN KEY (
			ad_no
		)
		REFERENCES MY_SCHEMA.TABLE19 (
			ad_no
		);

ALTER TABLE MY_SCHEMA.TABLE19
	ADD
		CONSTRAINT FK_TABLE2_TO_TABLE19
		FOREIGN KEY (
			id
		)
		REFERENCES MY_SCHEMA.TABLE2 (
			id
		);

ALTER TABLE MY_SCHEMA.TABLE19
	ADD
		CONSTRAINT FK_TABLE3_TO_TABLE19
		FOREIGN KEY (
			id
		)
		REFERENCES MY_SCHEMA.TABLE3 (
			id
		);

ALTER TABLE MY_SCHEMA.TABLE20
	ADD
		CONSTRAINT FK_TABLE14_TO_TABLE20
		FOREIGN KEY (
			co_no
		)
		REFERENCES MY_SCHEMA.TABLE14 (
			co_no
		);

